### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by TheFlagCourier** [CivWarsOSS/Marriage#2]
```
[08:29:31 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'marry' in plugin Marriage v2.0.21
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.4.jar:git-Paper-235]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-235]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1804) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1612) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$4712.0000000000000000.run(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-235]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-235]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassCastException: org.bukkit.configuration.MemorySection incompatible with java.lang.Boolean
        at net.civwars.marriage.commands.CommandMarry.execute(CommandMarry.java:38) ~[?:?]
        at net.civwars.marriage.internal.MarriageCommandExecutor.onCommand(MarriageCommandExecutor.java:37) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-235]
        ... 18 more
```

**Comment by TheFlagCourier** [comment]
Re-working repository, this is based on an older working set that was forcefully overwritten.
